In [1]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

In [2]:
# Tiến hành import dữ liệu vào xử lí
df = pd.read_csv("../../data/csv/cardiovascular_diseases.csv")

In [3]:
df.head()

,Unnamed: 0,ParentLocationCode,SpatialDim,Value,NumericValue,TimeDimensionBegin,TimeDimensionEnd,TimeDimensionValue,TimeDimType,TimeDim,IndicatorCode,Date
0,0,WPR,KOR,15.0 [13.6-16.5],15.012338,2015-01-01T00:00:00+01:00,2015-12-31T00:00:00+01:00,2015,YEAR,2015,BP_03,2024-04-29T15:59:45.237+02:00
1,1,AFR,GAB,34.2 [27.0-41.8],34.200390,2002-01-01T00:00:00+01:00,2002-12-31T00:00:00+01:00,2002,YEAR,2002,BP_03,2024-04-29T15:59:45.237+02:00
2,2,AMR,CAN,13.8 [10.5-17.5],13.821733,2008-01-01T00:00:00+01:00,2008-12-31T00:00:00+01:00,2008,YEAR,2008,BP_03,2024-04-29T15:59:45.237+02:00
3,3,WPR,SLB,21.1 [15.1-28.0],21.145140,2000-01-01T00:00:00+01:00,2000-12-31T00:00:00+01:00,2000,YEAR,2000,BP_03,2024-04-29T15:59:45.237+02:00
4,4,EMR,TUN,34.3 [29.5-39.3],34.258034,1999-01-01T00:00:00+01:00,1999-12-31T00:00:00+01:00,1999,YEAR,1999,BP_03,2024-04-29T15:59:45.237+02:00

In [4]:
# Có thể tiến hành drop cột Unamed:0
df.drop(columns=['Unnamed: 0'], inplace=True)
df.head()

,ParentLocationCode,SpatialDim,Value,NumericValue,TimeDimensionBegin,TimeDimensionEnd,TimeDimensionValue,TimeDimType,TimeDim,IndicatorCode,Date
0,WPR,KOR,15.0 [13.6-16.5],15.012338,2015-01-01T00:00:00+01:00,2015-12-31T00:00:00+01:00,2015,YEAR,2015,BP_03,2024-04-29T15:59:45.237+02:00
1,AFR,GAB,34.2 [27.0-41.8],34.200390,2002-01-01T00:00:00+01:00,2002-12-31T00:00:00+01:00,2002,YEAR,2002,BP_03,2024-04-29T15:59:45.237+02:00
2,AMR,CAN,13.8 [10.5-17.5],13.821733,2008-01-01T00:00:00+01:00,2008-12-31T00:00:00+01:00,2008,YEAR,2008,BP_03,2024-04-29T15:59:45.237+02:00
3,WPR,SLB,21.1 [15.1-28.0],21.145140,2000-01-01T00:00:00+01:00,2000-12-31T00:00:00+01:00,2000,YEAR,2000,BP_03,2024-04-29T15:59:45.237+02:00
4,EMR,TUN,34.3 [29.5-39.3],34.258034,1999-01-01T00:00:00+01:00,1999-12-31T00:00:00+01:00,1999,YEAR,1999,BP_03,2024-04-29T15:59:45.237+02:00

In [5]:
df.head()

,ParentLocationCode,SpatialDim,Value,NumericValue,TimeDimensionBegin,TimeDimensionEnd,TimeDimensionValue,TimeDimType,TimeDim,IndicatorCode,Date
0,WPR,KOR,15.0 [13.6-16.5],15.012338,2015-01-01T00:00:00+01:00,2015-12-31T00:00:00+01:00,2015,YEAR,2015,BP_03,2024-04-29T15:59:45.237+02:00
1,AFR,GAB,34.2 [27.0-41.8],34.200390,2002-01-01T00:00:00+01:00,2002-12-31T00:00:00+01:00,2002,YEAR,2002,BP_03,2024-04-29T15:59:45.237+02:00
2,AMR,CAN,13.8 [10.5-17.5],13.821733,2008-01-01T00:00:00+01:00,2008-12-31T00:00:00+01:00,2008,YEAR,2008,BP_03,2024-04-29T15:59:45.237+02:00
3,WPR,SLB,21.1 [15.1-28.0],21.145140,2000-01-01T00:00:00+01:00,2000-12-31T00:00:00+01:00,2000,YEAR,2000,BP_03,2024-04-29T15:59:45.237+02:00
4,EMR,TUN,34.3 [29.5-39.3],34.258034,1999-01-01T00:00:00+01:00,1999-12-31T00:00:00+01:00,1999,YEAR,1999,BP_03,2024-04-29T15:59:45.237+02:00

In [6]:
columns = ['SpatialDim', 'NumericValue', 'TimeDimensionValue', 'IndicatorCode']

In [7]:
# Lấy ra những đối tượng muốn xử lí
objectives = df[columns]

In [8]:
objectives.describe()

        NumericValue  TimeDimensionValue
count  231306.000000       236876.000000
mean       44.590119         2003.951840
std        77.295660            9.594262
min         0.500000         1975.000000
25%        20.900000         1996.000000
50%        33.300000         2004.000000
75%        46.200000         2012.000000
max      5736.000000         2021.000000

In [9]:
objectives.isnull().value_counts()

SpatialDim  NumericValue  TimeDimensionValue  IndicatorCode
False       False         False               False            231306
            True          False               False              5570
Name: count, dtype: int64

In [10]:
objectives.dropna(inplace=True)

C:\Users\lam01\AppData\Local\Temp\ipykernel_12980\1819294983.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  objectives.dropna(inplace=True)

In [15]:
objectives['IndicatorCode'].unique()

array(['BP_03', 'BP_04', 'BP_05', 'BP_06', 'NCDMORT3070',
       'NCD_HYP_CONTROL_A', 'NCD_HYP_CONTROL_C', 'NCD_HYP_DIAGNOSIS_A',
       'NCD_HYP_DIAGNOSIS_C', 'NCD_HYP_PREVALENCE_A',
       'NCD_HYP_PREVALENCE_C', 'NCD_HYP_TREATMENT_A',
       'NCD_HYP_TREATMENT_C', 'SA_0000001425', 'SA_0000001444'],
      dtype=object)